site_name: Entrega de Pr치cticas

nav:
  - Inicio: index.md
  - Pr치ctica de aula 1: practica1.md
  - Pr치ctica de aula 2: practica2.md
  - Pr치ctica de laboratorio 1: practicaLab1.md

theme:
  name: mkdocs
  custom_dir: custom_theme/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giselabcruz