site_name: Entrega de Prácticas

nav:
  - Inicio: index.md
  - PA 1: practica1.md
  - PA 2: practica2.md
  - PA 3: practica3.md
  - PL 1: practicaLab1.md

theme:
  name: mkdocs
  custom_dir: custom_theme/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giselabcruz